/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.channel.dropwizard;

import io.channel.dropwizard.health.DumbHealthCheck;
import io.channel.dropwizard.ping.resource.PingResource;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Bootstrap;
import io.dropwizard.core.setup.Environment;

public class App extends Application<AppConfig> {
    @Override
    public String getName() {
        return "hello-world";
    }

    @Override
    public void initialize(Bootstrap<AppConfig> bootstrap) {
        // nothing to do yet
    }

    @Override
    public void run(AppConfig configuration, Environment environment) {
        environment.jersey().register(new PingResource());
        environment.healthChecks().register("dumb", new DumbHealthCheck());
    }

    public static void main(String[] args) throws Exception {
        new App().run(args);
    }
}
