/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.channel.dropwizard;

import io.channel.dropwizard.health.DumbHealthCheck;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Bootstrap;
import io.dropwizard.core.setup.Environment;
import ru.vyarus.dropwizard.guice.GuiceBundle;
import ru.vyarus.guicey.validation.ValidationBundle;
import ru.vyarus.guice.validator.aop.DeclaredMethodMatcher;

public class App extends Application<AppConfig> {
    @Override
    public String getName() {
        return "hello-world";
    }

    @Override
    public void initialize(Bootstrap<AppConfig> bootstrap) {
        bootstrap.addBundle(GuiceBundle.builder()
            .enableAutoConfig("io.channel.dropwizard")
            .modules(new Module())
            .bundles(new ValidationBundle()
                .validateAnnotatedOnly())
            .build());
    }

    @Override
    public void run(AppConfig configuration, Environment environment) {
        environment.healthChecks().register("dumb", new DumbHealthCheck());
    }

    public static void main(String[] args) throws Exception {
        new App().run(args);
    }
}
